version: "3.7"
services:
  feecc-hid-reader-daemon:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: "host"
    privileged: true
    restart: on-failure
    environment:
      HID_EVENT_ENDPOINT: "http://127.0.0.1:5000/workbench/hid-event"
    volumes:
      - "/dev/usb:/dev/usb"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
